name: Build
'on':
  push:
    branches:
      - '*'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build and analyze
        env:
          GITHUB_TOKEN: d44f78a2-acfc-4ba5-ac99-f37307ce7277
          SONAR_TOKEN: 811c9a490983734401ba4e491eaefc8bfa7281de
        run: >-
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -Dsonar.projectKey=iamneo-production_d44f78a2-acfc-4ba5-ac99-f37307ce7277
          -Dsonar.login=811c9a490983734401ba4e491eaefc8bfa7281de
